name: Deploy to staging
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.LIVE_SERVER_USER }}
          key: ${{ secrets.LIVE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.LIVE_SSH_SERVER_PORT }}
          debug: true
          use_insecure_cipher: true
          script: |
            cd ${{ secrets.LIVE_APP_PATH }}
            git checkout master
            php artisan down
            git pull origin master
            /opt/cpanel/composer/bin/composer install --no-dev --no-interaction
            php artisan migrate
            php artisan view:cache
            php artisan up
